In [50]:
# Permet de tout executer au lancement du notebook + conserver le notebook actif pendant 2h
from IPython.display import Javascript
from masquer import *
Javascript("""
function repeter(){
IPython.notebook.kernel.execute("a=1");
}
// execute a = 1 en python toutes les 8 minutes pendant 2h
let timerId = setInterval(() => repeter(), 4800);
setTimeout(() => { clearInterval(timerId); alert('fin de cession'); }, 7200000);

// Supprimer la taille limite pour la sortie d'une cellule
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
};
IPython.notebook.kernel.execute("url = '" + window.location + "'");

// Exécuter toutes les cellule du notebook
    require(
        ['base/js/namespace', 'jquery'], 
        function(jupyter, $) {
            
                
                jupyter.actions.call('jupyter-notebook:run-all-cells-below');
                jupyter.actions.call('jupyter-notebook:save-notebook');
                Jupyter.actions.call('jupyter-notebook:hide-header')

        }
    );""")

<IPython.core.display.Javascript object>

# <span style="color:red;"><center>CHAPITRE 1 - Structures de données</center></span>

Une structure de données est l’objet informatique qui stocke des valeurs en mémoire. Nous allons ici n'en étudier que certaines. Pour caractériser une structure de données, il faut connaître les opérations possibles sur celle-ci et leur coût.


# I. Le Tableau

### I.1. Définition et propriétés

Le tableau est la seule structure de données présentée en première année.


Un tableau est une structure de données de même type (python autorise tout de même les tableaux dits hétérogènes c'est à dire d'éléments de type différents), modifiable, finie (les tableaux sont dynamiques en python) et telle que l’accès à un de ses éléments se fait en temps constant (on obtient la valeur d’indice i aussi rapidement peu importe la valeur de i)


Si les éléments du tableau sont positionnés en mémoire les uns à côté des autres à partir d’une adresse mémoire $m_0$ et que chaque élément du tableau prend la même place $m$ (d'où les éléments de même type), on trouve l’élément d’indice i à la position $m_0 + i\times m$ aussi rapidement **peu importe i**.


In [51]:
import time

#on crée un tableau de 1 000 000 d'éléments
a=[2]*1000000

# on mesure 10fois 1000000 d'appels à la première valeur
t=time.time()
for j in range(10):
    for i in range(1000000):
        a[0]
t=time.time()-t
print(t)

# on mesure 10 fois 1 appel à chacune des 1000000 de valeurs
t=time.time()
for j in range(10):
    for i in range(1000000):
        a[i]
t=time.time()-t
print(t)

# on mesure 10fois 1000000 d'appels à la dernière valeur
t=time.time()
for j in range(10):
    for i in range(1000000):
        a[-1]
t=time.time()-t
print(t)


# on mesure 10fois 1000000 d'appels à une valeur du tableau
t=time.time()
for j in range(10):
    for i in range(1000000):
        a[324598]
t=time.time()-t
print(t)

1.376288890838623
1.4820160865783691
0.8658647537231445
1.134103775024414


Chaque case du tableau garde son adresse mémoire mais est modifiable (la valeur stockée à cette adresse mémoire peut être changée)


In [52]:
# Création d'un tableau de 4 éléments
a = [1.27,2.45,3.798,4.142]

# Affichage du tableau et de l'adresse mémoire de a
print(a,hex(id(a)))

# modification d'un élément
a[2]=1.182

# Affichage du tableau et de l'adresse mémoire de a
print(a,hex(id(a)))

[1.27, 2.45, 3.798, 4.142] 0x7f5dbc723910
[1.27, 2.45, 1.182, 4.142] 0x7f5dbc723910


On voit bien que l'adresse mémoire de **a** n'a pas changé ici.

### I.2. Que peut-on faire avec un objet de type *list* en python ?

* Créer une liste vide

In [53]:
t = []

* ajouter un élément à la fin

In [54]:
t.append(3)
print(t)

t.append(6)
print(t)

[3]
[3, 6]


* Ou à la position que l'on souhaite

In [55]:
t.insert(1,5)
print(t)

[3, 5, 6]


* On peut écrire une valeur dans une case de la liste ou la lire

In [56]:
element = t[1]
print(element , t)

t[2] = 4
print(element , t)

5 [3, 5, 6]
5 [3, 5, 4]


On rappelle que les indices commencent à $0$ et vont jusqu'à $n-1$ en python pour une list de n élément.


La méthode **pop** permet de renvoyer un élément (par défaut d'argument, le dernier de la liste) et de le supprimer de la liste.

In [57]:
print(t.pop(),t)

print(t.pop(),t)

4 [3, 5]
5 [3]


Les méthodes **index(x)**, **count(x)** et **sort** permettent respectivement de renvoyer l'indice de la première occurence de x, le nombre d'occurences de x et de trier la liste.
Enfin **len(t)** renvoie le nombre d'éléments de t

In [58]:
t = [1,2,3,4,2,3,2,2,7]

print(t.index(3))
print(t.count(2))
t.sort()
print(t)
print(len(t))


2
4
[1, 2, 2, 2, 2, 3, 3, 4, 7]
9


### Exercice 1:
Programmez à la main ci-dessous une fonction **index2** et une fonction **count2**. Vous prendrez soin de documenter ces fonctions et de préciser clairement les arguments attendus en entrée.

In [ ]:
def index2():
    return

def count2():
    return


On peut aussi utiliser des indices négatifs qui permettent de pointer les éléments depuis la fin

In [59]:
t[-1]

7

Ou utiliser les slices:
* **t[ i : j ]** renvoie les éléments d'indice i à j-1
* **t[ : j ]** du début jusqu'à j-1
* **t[ i : ]** de l'indice i jusqu'à la fin

In [60]:
print(t[1:6],t[:8],t[6:])

[2, 2, 2, 2, 3] [1, 2, 2, 2, 2, 3, 3, 4] [3, 4, 7]


Enfin t[:] peut être utilisé pour faire une copie d'une liste, et un troisième indice permet de filtrer en imposant un pas.

In [61]:
s = t[:]
print(t,s)

[1, 2, 2, 2, 2, 3, 3, 4, 7] [1, 2, 2, 2, 2, 3, 3, 4, 7]


In [62]:
t[1:6:2] # les élément d'indices 1 à 5 incluspar pas de 2

[2, 2, 3]

In [63]:
t[: : -1] # Les éléments de la fin jusqu'au début par pas de -1

[7, 4, 3, 3, 2, 2, 2, 2, 1]

### Attention toutefois à la copie d'objets de type **list** car python est fait pour limiter l'usage de la mémoire ainsi:

In [64]:
t = [1, 2, 3, 4]
s = t # ne copie pas t. On a 1 seul objet référencé deux fois

# Pour preuve, l'adresse mémoire est la même
print(hex(id(t)),hex(id(s)))


0x7f5d9312f7d0 0x7f5d9312f7d0


In [65]:
t[0] = 4
print(s,t) # Les deux sont modifiées par la ligne précédente

[4, 2, 3, 4] [4, 2, 3, 4]


Une solution est de forcer la copie avec la syntaxe des slices.

In [66]:
t = [1, 2, 3, 4]
s = t[ : ]

# adresses mémoire différentes
print(hex(id(t)),hex(id(s)))

t[0] = 4
print(s,t) # seule t est modifiée

0x7f5d9311a050 0x7f5dbc723730
[1, 2, 3, 4] [4, 2, 3, 4]


Mais il y a encore plus perturbant, on peut **copier une *list* sans copier les sous *list***

In [67]:
t = [[1,2,3], [4,5,6], [7,8,9]]
s = t[:]

# adresses mémoire différentes
print(hex(id(t)),hex(id(s)))

# mais chaque sous tableau n'existe qu'une seule fois en mémoire
print(hex(id(t[0])),hex(id(s[0])))

0x7f5d931125a0 0x7f5dbc02fc30
0x7f5d931682d0 0x7f5d931682d0


Ainsi, si vous travaillez avec des matrices, il faudra utiliser la fonction **deepcopy** de la bibliothèque **copy** pour les copier afin d'éviter tout problème. 

In [68]:
t = [[1,2,3], [4,5,6], [7,8,9]]
s = t[:]

# pas de problème on modifie s[0] qui est bien différent de t[0] puisque s et t sont des objets différents en mémoire
s[0] = 0
print(s, t)

[0, [4, 5, 6], [7, 8, 9]] [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [69]:
t = [[1,2,3], [4,5,6], [7,8,9]]
s = t[:]

# problème on modifie s[0][0] qui est exactement le même que t[0][0], les deux listes sont modifiées
s[0][0] = 0
print(s, t)

[[0, 2, 3], [4, 5, 6], [7, 8, 9]] [[0, 2, 3], [4, 5, 6], [7, 8, 9]]


In [70]:
from copy import deepcopy
t = [[1,2,3], [4,5,6], [7,8,9]]
s = deepcopy(t)

# Cette fois ci pas de problème, deepcopy a fait une copie de l'ensemble des données
s[0] = 0
print(s, t)

[0, [4, 5, 6], [7, 8, 9]] [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### I.3. Avec numpy

Contrairement aux ***list*** de python, on a ici des tableaux qui sont **homogènes** (un seul type de données) et qui sont **statiques**. Il faudra donc définir à l'avance la taille de ces objets et le type des données contenues. Si le type n'est pas précisé, numpy le "devine" à partir des données fournies.
Un petit exemple avec des entiers:

In [74]:
import numpy as np
vect1 = np.array([1, 2, 3])
print(vect1)

vect2 = np.array([1, 2, 3], dtype=np.float)
print(vect2)

[1 2 3]
[1. 2. 3.]


Que se passe-t-il si on essaye de mettre autre chose dans ce tableau ?

In [75]:
vect1[1] = 3.7
print(vect1)

vect2[1] = 3.7
print(vect2)

vect1[2]="hello"
print(vect1)

[1 3 3]
[1.  3.7 3. ]


ValueError: invalid literal for int() with base 10: 'hello'

Soit une modification est possible sur la donnée (ici le float a été tronqué en int) et on conserve un tableau avec un seul type de données (attention la donnée a été modifiée sans avertissement!) soit on reçoit un message d'erreur si cela n'est pas possible (cas de la chaine de caractère)

Il faut donc bien faire la distinction entre les tableau "python" et les tableaux "numpy" qui n'ont pas les mêmes propriétés exactement car nous manipulerons les deux cette année.

<center> <a href="cours_01_1.ipynb">SUIVANT =></a></center>